### ISSUE TITLE
Does this method change the probability of the class?

### ISSUE THREAD

**Issue by CodingMice** [szq0214/MEAL-V2#8]
I am afraid of the distribute of dataset is different from the average of teachers?

**Comment by szq0214** [comment]
Hi @CodingMice, what you mean the distribution of dataset is different from the average of teachers? 

Since our supervision is only from the prediction of teacher ensemble without the hard labels, so the probability of the class will definitely be changed, this also can be regarded as recalibration.

**Comment by CodingMice** [comment]
That is what I want to know. BTW, if I use detect bagging method, can I get the approximate result of this method?  In other word, I wonder the importance of the D loss.

**Comment by szq0214** [comment]
@CodingMice I think you can try on the detection and such question is beyond the scope of this repo.
